### ISSUE TITLE
Use the same AMI for GC-classic and GCHP?

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/geos-chem-cloud#18]
Thanks to the fixes in geoschem/gchp#6, now GCHP can run correctly in the same software environment as GC-classic (Ubuntu 18.04, gcc 7.3.0, netCDF 4.6.0. The only addition is OpenMPI3). I see no reason of maintaining two separate AMIs, where the software libraries largely duplicate. This also avoids duplicating ~100 GB of minimum input data. 

Users can test GCHP immediately after playing with GC-classic on the cloud. Seems a great education opportunity for users.

My only concern is that GCHP might lag behind GC-classic's version. For example, when the new version of MAPL is implemented, it is not clear how much work it would take to make it run properly on the cloud.

If there're no objections I will use the same AMI for both.
@yantosca @lizziel @msulprizio

**Comment by yantosca** [comment]
I think it’s ok to use the same AMI for both GCC and GCHP for now.

KThe new MAPL might not be ready for a while.  We might have to build a new AMI once the new MAPL is ready, due to other software requirements.

If we can get people using GCC and GCHP in the cloud ASAP, then that’s huge!

Users can start with an AMI and git pull newer updates (e.g patches) as the model evolves.

Bob Y.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by lizziel** [comment]
Using the same AMI for both GC classic and GCHP would be ideal. We may need to update to gcc 8.2 for the new MAPL, but we can deal with that when it happens.

________________________________

**Comment by JiaweiZhuang** [comment]
Given that GCHP+gfortran is kind of buggy currently (#geoschem/gchp#15), maybe take GCHP down after the bug is fixed / after we actually use gfortran for benchmark? Or, I can just put it here purely for educational purpose but not scientific analysis.
