### ISSUE TITLE
HEMCO file missing for running GEOS-Chem 12.2.0 on AWS?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem-cloud#22]
Hi,

I am trying to running a 2x25 global complexSOA_SVPOA simulation on AWS using the latest GEOS-Chem. Again, I have followed all the steps from your tutorial except that:
I change the simulation period to 20130701-20130901 and I have downloaded all the met data. Then I encountered the following error copied from HEMCO.log
```
HEMCO ERROR: Cannot find file for current simulation time: /home/ubuntu/ExtData/HEMCO/CEDS/v2018-08/1712/NO-em-anthro_CMIP_CEDS_1712.nc - Cannot get field CEDS_NO_AGR. Please check file name and time (incl. time range flag) in the config. file
```
I then went to the s3://gcgrid to find that file ```aws s3 ls --request-payer=requester s3://gcgrid/HEMCO/CEDS/v2018-08/``` but unfortunately failed. Instead, I found ```NO-em-anthro_CMIP_CEDS_195001-201412.nc under s3://gcgrid/HEMCO/CEDS/v2018-04/```

It must be problem of this data missing or I need to change my configurations for this period?

**Comment by msulprizio** [comment]
Those files are available on the Harvard FTP site at http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/CEDS/v2018-08/ and should have been automatically synced to AWS S3. We are looking into it.

**Comment by FeiYao-Edinburgh** [comment]
> Those files are available on the Harvard FTP site at http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/CEDS/v2018-08/ and should have been automatically synced to AWS S3. We are looking into it.

Sorry I still have not seen a sub-directory called 1712 under v2018-08. I am confused why it appeared that the 2x25 complexSOA_SVPOA complained that for 20130701-20130901, whereas not for 20160701-20160901?

**Comment by msulprizio** [comment]
Correct. There is no 1712 subdirectory. CEDS emissions are only available for 1950-2014. The reason you are seeing the year 1712 in your error message is because of a quirk in HEMCO. When HEMCO can't find a file for a given year and the `C` flag for cycling/climatology is specified in HEMCO_Config.rc, HEMCO will continue to decrease the year until it finds a file. In this case, it gives up when it reaches the year 1712 and decided that it can't find the file. 

In the case of your simulation, HEMCO should be looking for `/home/ubuntu/ExtData/HEMCO/CEDS/v2018-08/2013/NO-em-anthro_CMIP_CEDS_2013.nc`. Can you verify that the 2013 file exists in that location? You can also try turning on HEMCO debug options (set VERBOSE and WARNINGS to 3 in HEMCO_Config.rc) and checking your HEMCO.log file for more information.

**Comment by FeiYao-Edinburgh** [comment]
Can you verify that the 2013 file exists in that location?

No. I run GEOS-Chem on Cloud and thought that HEMCO directory was complete. I have pulled them from S3 to EC2 and it now seems running smoothly.

Thanks for your debugging tips, too!

**Comment by FeiYao-Edinburgh** [comment]
I just found CONUS_Mask.01x01.nc file is missing in ami-06f4d4afd350f6e4c: ~/ExtData/HEMCO/MASKS/v2018-09. Nevertheless, I can download it from s3://gcgrid/.

**Comment by yantosca** [comment]
Thanks for letting us know.  I am going to create a new AMI once version 12.3.0 ships, and I'll make sure that file is included.
