### ISSUE TITLE
no rule to make target mpbuild

### ISSUE THREAD

**Issue by RajMLal** [geoschem/geos-chem-cloud#31]
Hi Jiawei,

I am trying to run a geosfp_2x2.5_standard run on AWS. I've followed the instructions given here (https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/research-workflow.html#get-source-code-and-checkout-model-version) including making a GC directory, downloading the source code and Unit Tester, and changing the copyrundirs.input file with the appropriate information (GCGRID_root, data_root, etc.). 

I went into the run directory and tried to compile (make realclean worked, make -j4 mpbuild NC_Diag gave an error). 

Do you have any thoughts why this may have happened?

Best,
Raj
![mpbuild error](https://user-images.githubusercontent.com/57201024/67907687-28fa6f00-fb4f-11e9-8543-0368594c336a.png)

**Comment by JiaweiZhuang** [comment]
Which model version do you use? Did you checkout the proper version by `git checkout 12.1.0`, for both source code and unit tester?

**Comment by yantosca** [comment]
If you are using the 12.6.0 AMI, you can use “make -j4 build”.  That was changed in I think 12.4.0 and higher.  Sorry about that, I did not get around to updating the doc yet (we are all a bit slammed here this week).

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by RajMLal** [comment]
Thank you Jiawei and Bob! 

The "make -j4 build" command works for me and the code is compiling. 

~Raj

**Comment by JiaweiZhuang** [comment]
Glad to see this!

**Comment by yantosca** [comment]
Also, you can always type “make help” for a list of compilation options.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lizziel** [comment]
Hi Raj,

What version of GEOS-Chem are you using? In newer versions of GEOS-Chem the build commands have changed. Type ‘make help’ to see the options. You may need to use build rather than mpbuild.

Best,
Lizzie

--
Lizzie Lundgren
Senior Scientific Programmer
GEOS-Chem Support Team
geos-chem-support@g.harvard.edu<mailto:geos-chem-support@g.harvard.edu>

Please direct all GEOS-Chem support emails to the entire GEOS-Chem Support Team<http://wiki.geos-chem.org/GEOS-Chem_Support_Team>. If you are reporting a bug, please create an issue on GitHub<https://github.com/geoschem/>.
