### ISSUE TITLE
[QUESTION] AMI version to use?

### ISSUE THREAD

**Issue by LukeAParsons** [geoschem/geos-chem-cloud#45]
I am new to running GEOS-Chem, and just set up an AWS account to try to follow the tutorial (https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/quick-start.html). However, I noticed that the screen shots and options in the tutorial are not the same as what I see on AWS's website.

For example:

1) there are several newer versions of the GEOS-Chem tutorial on the AMIs pull down- should we be using the one in the tutorial, or the latest version of the tutorial I see on AWS? Or does it matter? And if it matters, do newer versions require different computing resources than those suggested in the older version of the tutorial?

2) the tutorial's Choose an Instance Type step suggests 'r5.large'- although this is an option in the current AWS interface, the information does not look the same on AWS as the tutorial screen shot shows. The default on AWS is 't2.micro', which is 'Free tier eligible', but 'r5.large' is listed as 0.126 USD/hour- are we charged to run the tutorial if we choose the suggested r5.large, or is this just for longer runs using more computing time? Please advise.

I would appreciate updated screen shots or tutorial information that matches with the interface that we now see on AWS so I know if I am 'doing it right' as I learn for the first time (or even information that says 'updates don't matter, please follow directions even if the screen shots no longer match')

Thank you for all of your time and effort- this is a great resource.

**Comment by yantosca** [comment]
Thanks for writing @LukeAParsons.  We have recently started offering GEOS-Chem on the AMI Marketplace (with the current machine image) so this page may be helpful:
- https://aws.amazon.com/marketplace/pp/prodview-wu7jnvdqc5qnu?sr=0-2&ref_=beagle&applicationId=AWSMPContessa

As for the instance type, a good choice might be c5.2xlarge or c5.4xlarge, depending on the type of simulation you wish to do.

We realize that some of the doc is out of date and we ask for your patience.  The person who set up the doc has moved on from our group.  Also some of the AWS console controls have been updated from what is represented on the page.  We hope to be able to address this in the near future.

**Comment by LukeAParsons** [comment]
Thank you very much for the prompt reply- I followed the link you provided, but it only partly answers my questions related to the tutorial:
Do you suggest new users still run the tutorial (https://cloud-gc.readthedocs.io/en/latest/chapter02_beginner-tutorial/quick-start.html) as closely as they can given the updated AWS options/interface? And can new users still go through the tutorial for free using the suggested c5.2xlarge instance type, or should we avoid following the old tutorial instructions?

**Comment by yantosca** [comment]
Thanks for your patience @LukeAParsons.  A couple of things:

1. Please update your link to https://geos-chem-cloud.readthedocs.io (aka http://cloud.geos-chem.org).  The cloud-gc.readthedocs.io is orphaned.  When that was originally set up, ReadTheDocs allowed you to select a name different from the GitHub repository that is used to store the documentation but that is no longer possible.  So the geos-chem-cloud.readthedocs.io now matches the https://github.com/geoschem/geos-chem-cloud repository name.

2. It would probably still be of benefit to go through the AWS cloud tutorial at this link: https://geos-chem-cloud.readthedocs.io/en/latest/chapter02_beginner-tutorial/quick-start.html.

We wiil try to overhaul the cloud documentation but at this point it won't happen until into the new year.

Tagging @msulprizio @lizziel @Jourdan-He @SaptSinha @laestrada

**Comment by laestrada** [comment]
Hi @LukeAParsons,

You should be able to (mostly) follow the first 4 steps of the [quick-start documentation for the imi](https://imi.readthedocs.io/en/latest/getting-started/quick-start.html), which has updated images for the new aws console GUI. The configuration of the aws instance is the same as for GCClassic -- just make sure to select the [GCClassic AMI](https://aws.amazon.com/marketplace/pp/prodview-wu7jnvdqc5qnu?sr=0-2&ref_=beagle&applicationId=AWSMPContessa) that Bob referenced above instead of the IMI AMI. The IMI suggests c5.9xlarge, but that is not necessary for running gcclassic. This should get you to the point of logging into the instance and from there you can follow the original tutorial.

On your question of cost, running an instance on aws is billed by each hour the instance is running + any storage costs. The t2.micro is in the free-tier of aws, but it does not have enough computational power to run GCClassic. r5.large (2 cpus, 16GB mem, ~$0.12/hour) should work for just running the tutorial simulation. c5.2xlarge (8 cpus, 16 GB mem, ~$.30/hour) will significantly improve the performance of GCClassic. You can check the cost of each instance type in your region using [this ec2 pricing tool](https://aws.amazon.com/ec2/pricing/on-demand/).

**Comment by LukeAParsons** [comment]
Thank you @laestrada for your prompt feedback. I was able to get some 1-month tester runs done and run the tutorial after reading your response.
